### PR TITLE
FE | Initial GraphQL Query

### LINKED ISSUE #3: FE Research GraphQL

### PR DESCRIPTION
**Pull request by mikeharrison57**
# Pull Request

**What does this PR do?**

- Install apollo/client package.
- Installed gql package.
- Set up initial GraphQL query.
- Display data on home page via the Kitchen and Preview components (see displayed data in screenshot below).
- Fix image bug for Kitchen component (see Kitchen icons in screenshot below). 

Screen Shot 2022-08-30 at 4 23 56 PM

**Why were these changes implemented?**

- Apollo/client and gql were installed to leverage the apollo/client library in conjunction with GraphQL, which allows us to make requests to our BE GraphQL server. 
- Created initial query to display basic data on the main page of our application. 

**Issues**

- closes #3

### CODE REVIEW

**Comment by omegaeye-he** [comment]
I like all the commits, any tests?

**Comment by mikeharrison57** [comment]
> I like all the commits, any tests?

Hello Khoa! Thank you for your comment. We're going to be writing End to End tests at the end of our project leveraging the Cypress.io testing framework. 

However, for the purposes of this Front End application, this will be the only testing that we conduct. Based on the Capstone Rubric, we believe that this is the expectation from us as the FE team.

**Comment by omegaeye-he** [comment]
> However, for the purposes of this Front End application, this will be the only testing that we conduct. Based on the Capstone Rubric, we believe that this is the expectation from us as the FE team.

I understand that FE testing is a little tricky. How then are you verifying that everything is working? even if you're doing Browser Driven Development, at least make a note in the PR message, and send a link so your code reviewer can see a visual of what you did.

**Comment by mikeharrison57** [comment]
> > However, for the purposes of this Front End application, this will be the only testing that we conduct. Based on the Capstone Rubric, we believe that this is the expectation from us as the FE team.
> 
> I understand that FE testing is a little tricky. How then are you verifying that everything is working? even if you're doing Browser Driven Development, at least make a note in the PR message, and send a link so your code reviewer can see a visual of what you did.

Currently we are verifying it by starting our localHost server and seeing what displays in our DOM and console. 

That makes sense. Thank you for suggesting that Khoa. I just added a screenshot to the PR that showcases the data and images being displayed on our DOM.

**Review by masaki-kleinkopf — COMMENTED** [review]
Nice start on this home page. We will work on the location pages next.

**Review by omegaeye-he — APPROVED** [review]
lgtm

**Pull request merged**
